build: false

environment:
  matrix:
    - python: 27
#    - python: 35

install:
  - "SET PATH=C:\\Python%PYTHON%;c:\\Python%PYTHON%\\scripts;%PATH%"
  - "python.exe -m pip install lxml==3.6.0"
  - "python.exe -m pip install ."

test_script:
  - "kissanime-dl https://kissanime.to/Anime/Kuma-Miko-Girl-meets-Bear . --simulate --verbose"

